### ISSUE TITLE
web2py.js web2py_websocket onclose bug

### ISSUE THREAD

**Issue by sasogeek** [web2py/web2py#1022]
After specifying all 4 parameters of the web2py_websocket function in web2py.js, only the url, onmessage and onopen parameters seem to work. onclose doesn't execute when client disconnects/socket closes.

More information in this thread https://groups.google.com/forum/#!topic/web2py/l-03-Ymauy4

**Comment by niphlod** [comment]
this can't be a bug. onclose gets transparently proxied to the native WebSocket object. If you have issues with it it's probably because onclose is flaky at most. Can you provide a sample where web2py_websocket doesn't work while the native websocket works ?

If not, I'm going to close this in a few days.
