### ISSUE TITLE
saml2_auth.py probrably bug and solution

### ISSUE THREAD

**Issue by josedesoto** [web2py/web2py#1028]
Creating a SAML2 SP with web2py I stuck in this error:

```
 File "/home/jose/Documents/DESARROLLO/web2py-sp/web2py/gluon/contrib/login_methods/saml2_auth.py", line 113, in login_url attributes = d['response'].assertion.attribute_statement[0].attribute
AttributeError: 'dict' object has no attribute 'assertion'
```
This error is raised when the IDP  issues a <Response> message to be delivered by the user agent
to the web2py service provider. As I could read in OASIS documentation, in this step the binding can be a HTTP POST, or HTTP Artifact to transfer the message. In web2py saml2_auth.py it looks that still using HTTP REDIRECT.

Does anyone has the same error?

A probable solution could be by modifying: **./gloun/contrib/login_methods/saml2_auth.py**:

1. Add on the top: ```from saml2 import BINDING_HTTP_POST```

2. line 62: replace: bindings = [BINDING_HTTP_REDIRECT] to ```bindings = [BINDING_HTTP_REDIRECT, BINDING_HTTP_POST]```

3. line 74 (after else) add: ```binding = BINDING_HTTP_POST``

**Comment by josedesoto** [comment]
I have been doing some more tests:

1. With http://idp.oktadev.com when the IDP  issues a message to be delivered by the user agent to the web2py service provider. Okta perform a POST.

2. With the PYSAML2 IDP example, perform a GET to deliver the <Response> message.

Looking into the OASIS documentation: 
http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#5.1.2.SP-Initiated%20SSO:%20%20Redirect/POST%20Bindings|outline 

It looks that the step 6 ( <Response> message) should be a HTTP POST, not sure why PYSAML2 IDP example perform a GET.

To make saml2_auth.py works in web2py for both cases, for now I have added:

```
    if request.env.request_method == 'GET':
        binding = BINDING_HTTP_REDIRECT 
    elif request.env.request_method == 'POST':
        binding = BINDING_HTTP_POST 
```

**Comment by mdipierro** [comment]
Can you post a patch or a pull request or email me the modified file?

**Comment by borgand** [comment]
This fixes the issue for me too (SimpleSAMLphp as the IdP)

:+1:

**Comment by borgand** [comment]
On a side note - this patch fixes the issue only for `AuthnResponse`, but `saml2_auth.py` still uses `REDIRECT` binding for all `AuthnRequest`s, regardless whether the IdP actually supports it.

This is because at the moment when above code is run, the `request.env.request_method` will always be `GET` because "Log In" link makes a `GET` request to the web2py server, but this has nothing to do with the SAML binding.

A correct solution would be to peek at IdP metadata and see what bindings are listed in `md:SingleSignOnService` element and pick one to use with `AuthnRequest`.

**Comment by timnyborg** [comment]
> On a side note - this patch fixes the issue only for `AuthnResponse`, but `saml2_auth.py` still uses `REDIRECT` binding for all `AuthnRequest`s, regardless whether the IdP actually supports it.
> 
> This is because at the moment when above code is run, the `request.env.request_method` will always be `GET` because "Log In" link makes a `GET` request to the web2py server, but this has nothing to do with the SAML binding.
> 
> A correct solution would be to peek at IdP metadata and see what bindings are listed in `md:SingleSignOnService` element and pick one to use with `AuthnRequest`.

This is an issue.  I have to hardcode BINDING_HTTP_POST into the line:
`req_id, req = client.create_authn_request(destination, binding=binding)`
replacing 'binding', or else I'm unable to work with my idp, which will not support Redirect for SSO service.  

Meanwhile, the line
```
http_args = client.apply_binding(binding, str(req), destination, relay_state=relay_state)
```
must ALWAYS use Redirect, as only that binding will produce the 'Location' header needed in the next line.

If anyone can point me in the right direction re. how to get the metadata's available SSO bindings via pysaml, I'd be happy to try to patch this.

**Comment by tyctor** [comment]
i triyed saml2 auth with `saml2_auth.py`
but instead of `POST` request to my IdP, it making `GET` request with `SAMLRequest` attached to query string
but IdP is accepting only `POST` so it is not working
i have same setup id django and it is working as expected with `POST` request
are you sure that  `saml2_auth.py` is working?
