### ISSUE TITLE
Feature request: explicit BEAUTIFY truncate length

### ISSUE THREAD

**Issue by ailnlv** [web2py/web2py#1040]
Right now, calling `BEAUTIFY` truncates strings to some default value. It would be great if `BEAUTIFY` could receive a `truncate` parameter just like `SQLTABLE`, which could also be set to `None`.

**Comment by niphlod** [comment]
Can you post an example ?

**Comment by ailnlv** [comment]
I think the problem only exists when beautifying Rows objects. Ensure that there is some table with at least one string field, with strings longer than 20 characters or so. Then call

    >>> BEAUTIFY(db().select(db.sometable.stringfield, limitby=(1,2))).xml()
    '<div><table><thead><tr><th>sometable.somefield</th></tr></thead><tbody><tr class="w2p_odd odd"><td>1111111111111...</td></tr></tbody></table></div>'

If you scroll to the right, you'll see that the call trims the string at some point, and there's no way to avoid it when calling BEAUTIFY over a Rows object.

**Comment by niphlod** [comment]
uhm, this is funky. SQLTABLE has a LOT of parameters, and agreeing to pass "truncate" to BEAUTIFY (in order to pass it down to SQLTABLE) opens the possibility to pass practically any other parameter down with it.
If the only issue is BEAUTIFYing a Rows, use SQLTABLE.
IMHO BEAUTIFY is useful only for development and is not intended to be used in production.

unless @mdipierro has something to say on this, I'd close this in a few days.

**Comment by ailnlv** [comment]
Well, BEAUTIFY.__init__ already takes an `attributes` dict, which is passed to a bunch of stuff. I just have no idea of where to add it so that SQLTABLE gets it.

**Comment by niphlod** [comment]
it just takes 'sorted' and 'keyfilter'. Everything else is passed to - basically - TABLE as it is, which in turns gets passed to DIV. Intercepting 12 attributes (linkto, upload, orderby, headers, truncate, columns, th_links, extracolumns, selectid, renderstyle, cid, colgroups) plus making an exception for SQLTABLE inside BEAUTIFY for the sole purpose of not truncating a SQLTABLE when embedded in a BEAUTIFY tag - which again is NOT meant for production sites - is quite a stretch.
