### ISSUE TITLE
Default AppConfig.ini vs application AppConfig.ini

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1093]
Can we have a default AppConfig that could be in web2py tree (not in the app folder) and an application AppConfig.ini which is in the app folder?

This may resolve this kind of issue : https://groups.google.com/d/msg/web2py/EKCgmsd5klQ/ExQM1MidBQAJ

I remember having issue with AppConfig when I first used it.

Also, the way it is remember me the issue we have with static/* content required by web2py...

Thanks for consider this proposition

**Comment by niphlod** [comment]
there can be only one istance of appconfig per app. 
The whole point is to provide a fast access to every REQUIRED configuration value (if the app doesn't find a REQUIRED value, it should raise an exception, or handle the fact it's missing).
Everything else (variables) is demanded to the application (what to do if a parameter is missing is app-specific, not web2py-specific).
I don't see the point on merging something that doesn't comes with the app (the "external" config) with what AppConfig provides.
Unless a PROPER usecase emerges I'm going to close this as an incorrect bug report in a few days.

**Comment by BuhtigithuB** [comment]
The point is to have an AppConfig which can be override by a user difined
AppConfig, so in case user mess something the official AppConfig is still
there...

Maybe ".AppConfig" can be use if as you explain AppConfig is app specific
and should stays at app level...

I just thought that as many other parameters that are defaulted in web2py
they can be override by the user and I think this should be the case with
AppConfig parameters too, which is not the case actually... web2py relying
entirely on AppConfig.

So, missing value in AppConfig result in unworking app which wouldn't be
the case with sane default.

Also, when you change parameters into AppConfig and they failed you don't
have meaning full traceback error which is I guess the issue describe by
Donald in the first place...

**Comment by niphlod** [comment]
Donald didn't report any exception. He just asked for directions. 
Once again, I'd really like to see a real example.
web2py doesn't rely on AppConfig. It's your app that optionally relies on it.
If the user "messes" with the config values, and your app want to be user-resilient, you can code your own fallback. 
If instead your app won't accept a messed-up parameter, and you want to be user-friendly, you can raise your own exception.
If instead your app shouldn't even start, you can stop there.
If the whole deal is a default value if a config item is missing, I reaaaaaaally don't see an issue in using myconf.get(conf_key, default_value) (it's a dict, for everybody's sake)
Moreover, inheriting from a "default" config will probably mess up who has applications that are "user-resilient" and "not user-resilient" in the same web2py instance (which, BTW, is kinda my 100% scenario).

**Comment by alex0834** [comment]
I think the inconvenience happens when retrieving a value which is not present in the config file. Simply using myconf.get(conf_key, default_value) won't work because of the sections in the config file, e.g. you'd have to write something like myconf.get('db', {}).get('uri', 'sqlite://storage.sqlite')

by adding a default parameter for the 'take' method you could write:
myconf.get('db.uri', default='sqlite://storage.sqlite')

This would be a nice and easy addition. It would also allow to add new parameters to the config file, deploy the application and use the default values without updating the config file and restarting the server (to reload the config file).

**Comment by niphlod** [comment]
appconfig is built for speed. It parses values and stores in cache in order to do that thing one time only (ideally, when the first request for the app comes in). 
Allowing a default value would result in caching the default value. This could bring to intricacies where you are in a state not knowing if the value came from the config or the default value.
Moreover, the defined usecase for 
"""
add new parameters to the config file, deploy the application and use the default values without updating the config file and restarting the server
"""
isn't really clear. If you really need a default value, it's because it could be missing from the appconfig WHEN the app is already deployed. 
If you add a new parameter to the config AND you deploy the app, the code will pick it up without the need of restarting the webserver.

**Comment by alex0834** [comment]
I didn't have the mentioned use-case so far (since I've just recently switched to appconfig) but I assume it will happen. How does the code know when to pick up the new config? I'm not deploying through the GUI, basically I'm just copying the application folder on the server.

"""
This could bring to intricacies where you are in a state not knowing if the value came from the config or the default value.
"""
Isn't this also the case when changing an existing value in the config file? I guess the config file is not reloaded when the file was modified?

Anyway, I probably won't need a default value but I think it would come in handy sometimes.

**Comment by niphlod** [comment]
as soon as you myconf.take('foo.bar') the value is stashed into cache. 
If you want to reload appconfig to see if some values are changed, either you pass reload=True or you restart the server.
If you're deploying copying over you probably don't mind performances (or you're in a "development mode"), so if you want flexibility over performances, stick with reload=True.
In "expert mode", you'd copy over the app, compile it, then touch the webserver process (usually wsgi). The implicit restart will effectively reload the app AND the config.

In all of this I'm still missing a solid usecase for a default value, but it's not hard to implement. It'll probably be harder to document, for the cache-speedup related piece of code.
Feel free to send a PR to add a "default=None" to the take() function, plus the related API docstrings.
