### ISSUE TITLE
Error when validator label is a function

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#1097]
A while ago I defined a validator like that
```
IS_IN_DB(db, 'table.id', function)
```
function takes the row as first argument and returns a string. It used to work with former web2py (2.10.x) but latest master.
Reverting https://github.com/web2py/web2py/commit/65c87386c12513bbcf32674861ead171260c95ed introduced by @nklever fixed it.

**Comment by niphlod** [comment]
PS this is the second issue raised and blaming that commit. Does ANYONE recall why was it committed ? @mdipierro , @abastardi , @nklever itself ? 

:-D

**Comment by abastardi** [comment]
Well, first, it appears there is a bug in that commit -- in the `else` block, it should be `records.render()`, not `records.render`.

Also, if I'm reading it right, I think it breaks backward compatibility, and doesn't generally seem like the desired behavior. Rather than passing the raw record values to the `label`, it is passing the rendered values (by applying each field's `represent` function). I don't see why you would want to force this behavior (I'm sure it's convenient in some cases when you simply want the labels to be the "represented" values, but then you lose the ability to do anything with the original values).

**Comment by niphlod** [comment]
ok, it pretty much agrees with what I was thinking. IMHO it's to revert.

**Comment by abastardi** [comment]
I agree.

**Comment by mdipierro** [comment]
I agree. It is done.
