### ISSUE TITLE
service does not start

### ISSUE THREAD

**Issue by RekGRpth** [web2py/web2py#1142]
because thereis syntax error in file scripts/service/service.py on line 95:
```python
        if 'log_filename' in config.key():
```
but must
```python
        if 'log_filename' in config.keys():
```
and on line 77:
```python
                interfaces.append('%s:%s:%s:%s' % (ip, port, cert, key))
```
but must
```python
                interfaces.append('%s:%s:%s:%s' % (ip, port, key, cert)
```

**Comment by niphlod** [comment]
Fixed with https://github.com/web2py/web2py/pull/1145 but I highly suggest you using the recommended - from some time now - way to use web2py as a service through nssm.exe which you can read upon [here](http://web2py.com/books/default/chapter/29/13/deployment-recipes#Using-nssm-to-run-as-a-Windows-service)

**Comment by RekGRpth** [comment]
Thank You, but I' using it under ubuntu server
