### ISSUE TITLE
minor auth.add_membership bug

### ISSUE THREAD

**Issue by alex0834** [web2py/web2py#1204]
When using auth.add_membership with role parameter the user groups are not updated in the session. Easy fix is to always execute
self.update_groups()

**Comment by BuhtigithuB** [comment]
Sorry to be offtopic, but could "auth.user_groups" be in sync with the same
trick?

I use auth.user_groups, but sometimes need to log off and logon again to
make it up to date in order for the feature that I develop around it works
properly, it not a big deal because it happens only once it a wild that it
cause issue, but why would auth.user_groups not always accurate with the
state of membership of the user??

Thanks

Richard

**Comment by BuhtigithuB** [comment]
Nevermind, I think it because I don't use auth methods to populate the
database that it the cause of my issue...

**Comment by alex0834** [comment]
that happens when you update auth.user_groups yourself, I also had this problem. Just use the methods of Auth class (e.g. auth.add_membership) to be on the safe side, where the groups are also updated in the session. Unless you use role parameter for auth.add_membership as described in this bug.

**Comment by BuhtigithuB** [comment]
It makes me take conscient that I should use auth methods instead of
insert/update information in auth_tables directly... As you mention, yes
auth.user_groups should be up to date if auth methods are used...

Thanks

**Comment by niphlod** [comment]
IMHO the bug is not-existent. self.update_groups() is definitely NOT the answer: it just works on the current session, so if you called add_membership() to the user currently logged in.
if you add(ed)_membership on another user, it wouldn't work.

group membership in session is ONLY updated at login-time, and it's done to preserve resources, as with ANY other RBAC solution.
has_membership checks membership on the tables and not on the session, if in need to check for a particular permission that needs absolute "transactional" check of membership.
If you are checking for membership through session's user_groups, than you are ACCEPTING the tradeoff of not using has_membership(). 

Feel free to comment further, but I really don't see the point of having this issue opened.

**Comment by alex0834** [comment]
yes, I'm using the session's user_group (auth.user_groups) since I don't want db access to check permissions for every user request. Initially I directly updated auth.user_groups (as BuhtigithuB) when membership of a user changed. On the next request the new membership was not there in auth.user_groups because it was not updated in the session. The membership was only available after the user logged in again.

Later I replaced manually updating auth.user_groups and instead used add_membership method which also updates the user_groups in the current session. Then everything was fine.

But if you use add_membership with role parameter as I initially mentioned then it still wouldn't work as expected. For me I doesn't make a difference (since I don't use role parameter) but I still think this is a bug which should be fixed.

**Comment by niphlod** [comment]
once again, it's not a bug. You're misusing a functionality assuming it would work the way you want to. 
And your proposed fix won't work on all cases. If you want to manage membership yourself, do it from the top bottom (including this particular corner case).

**Comment by alex0834** [comment]
sorry, I don't get it. Why am I misusing a functionality? I'm using add_membership to add a new membership (on a request made by the user who gets the new membership), this also updates user_groups in the session. So on the next request auth.user_groups contains the new group and everything is fine. Whats wrong with this approach?

I just wanted to point out it behaves differently when role parameter is used - which I don't, so it doesn't matter for me but could matter for others...

**Comment by niphlod** [comment]
I'm not sure either what the bug is opened for. 
add_membership is not restricted to the same user doing the request. 
Checks on membership throughout all auth's code is done on tables. 
If you want to short-circuit a query using your own method based on group membership as specified on the session, then you're effectively rolling your own, and you're the responsible of properly updating (and saving) session.

**Comment by alex0834** [comment]
If the user_groups are not used from the session and everything is done on tables that's fine, although I'm curios why it's even stored in the session if it's not used. 

The problem is the inconsistency. The behavior of the method depends on which parameter is used (either group_id or role) when both parameters have the same purpose and only specify a group. With group_id the groups are updated in the session and with role they are not - it doesn't matter if this is internally used or not. In my opinion that's bad and can lead to errors. If you think that is fine and good code then leave it as it is and close this bug. I just wanted to help to improve code quality...

**Comment by mdipierro** [comment]
Niphlod is right. Reverting.
