### ISSUE TITLE
Python 2 incompatibility

### ISSUE THREAD

**Issue by nursix** [web2py/web2py#1409]
This:

https://github.com/web2py/web2py/blob/master/gluon/sqlhtml.py#L62

doesn't quite add up - either it is ```func_code``` and ```func_defaults``` (Py2), or it is ```__code__``` and ```__defaults__``` (Py3). Crashes in Python 2.7 with AttributeError for callable classes.

**Comment by nursix** [comment]
This variant works:

    if hasattr(f,'func_code'):
        n = f.func_code.co_argcount - len(f.func_defaults or [])
        if getattr(f, '__self', None):
            n -= 1
    elif hasattr(f, '__code__'):
        n = f.__code__.co_argcount - len(f.__defaults__ or [])
        if getattr(f, '__self__', None):
            n -= 1
    else:
        n = 1

**Comment by niphlod** [comment]
@ilvalle : thoughts ? those are more or less the same "smelly" findings I reported a while back.

**Comment by ilvalle** [comment]
@nursix thanks for reporting.
In PY3 ```field.represent``` should take two parameters and users should not be allowed in defining it with only one parameter.
It's worth to notice that if an user wants to use SQLFORM.grid() it is already forced to define ```field.represent()``` with two parameters on the other hand (I guess for backward compatibility) SQLFORM and SQLTABLE accept ```field.represent()``` defined with one parameter.
As a result, since py3 already requires the code to be changed, do you agree in forcing py3 users in always defining ```field.represent()``` with two parameters?

**Comment by nursix** [comment]
@ilvalle I don't think that's the problem I was reporting (which was the mismatch of introspection attributes), but since you're asking for my opinion, I would tend to disagree.

We're maintaining a very large application that makes extensive use of Field.represent (but not SQLFORM.grid()), and in most of the cases with only one parameter.

Being forced to rewrite so many functions due to a backwards-incompatible framework change is therefore a massive deterrent against a migration to Py3.

And if backwards-incompatible changes in web2py/PyDAL would cause us more migration effort than forking the pair and implementing backwards-compatible alternatives, then you can guess which route we would have to take - and that would be a pity after almost 10 years with web2py.

It has already become a lot more laborious to keep up with backwards-incompatible changes (and bugs), mainly in PyDAL, over the past year - more effort in the last 12 months than in the 8+ years before ;)

So I would plead for making the Py3 migration path as easy and manageable as possible, and especially not to force the implementer community to rewrite even larger parts of their mighty web2py applications that took them 10 years to develop.

You always used to be the nice guys ;) so I'm hopeful that will continue to be the case.

(Obviously, that doesn't concern any new functionality - or such that is still marked as "experimental". For that I totally understand that backwards-compatibility is not the priority).

**Comment by nursix** [comment]
P.S. It is unlikely that we will migrate to Py3 any time soon since we have both mission-critical deployments and a range of downstream projects most of which lack the resources to follow through with a forced migration, whilst there is no real value gain.

Therefore, we appreciate the full Py2 support that we have in web2py today (including backwards-compatibility as it used to be) - and would be rather disappointed if that would be broken deliberately.

Of course we accept that certain pain points need to be resolved and backwards-compatibility be sacrificed occasionally, and we will continue to adapt - as long as we can manage it. But if it is not absolutely necessary to sacrifice it, then it is gold to maintain it (one of the reasons why we chose web2py in the first place ;))

**Comment by ilvalle** [comment]
I've added an unittest for such issue, see https://github.com/web2py/web2py/pull/1419/commits/461e29076867febced4fa2a11b0eebe4ad18220d

Regarding the number of parameters, the point is that any migration to python 3 requires the code to be adapted, as a result it isn't backward compatible.
In this case, you have to add an *unused* parameter to the function definition of each ```field.represent```;  for me it could be the right moment to update it, @niphlod @mdipierro what do you think?

**Comment by niphlod** [comment]
I do agree with all of the above, EXCEPT that we can't really fathom every possibile usage (and mis-usage) without users adding regression tests and/or reporting bugs. 
Reporting that "we spent more effort in the last 12 months than the last 8 years fixing app's code for web2py's faults" in my POV leads to new features being excessively more useful than staying with an older version (i.e. the time spent adapting code is a well-received compromise in order to gain access to new features, vs reporting the bug and waiting it to be fixed). If that was indeed a complaint, my reply would be that nobody is forcing you to upgrade to the latest release, and everything is opensource and publicly available.
IMHO complaints can be raised when NEW and critical regressions are immediately reported but fixed only months later (there are certainly bugs that NEED closure, but doesn't seem to be this the case, 13 days old).
A more rational "flow" SHOULD be that we (developers) do whatever we can do to improve code and add new features (py3 compat is long overdue, and asked by a fair majority) and you (from small to heavy users) report bugs. If you happen to have tests to be added to the test-suite to AVOID once and forever that ANY commit WON'T ever break a particular feature, it'd be a win-win: "old" and "new" developers can happily hack the code knowing what is expected to output, and you can happily live ever after without incurring in "efforts". I don't think it's actually written anywhere, but it's been on for a while the implicit "stop" to a PR that doesn't pass tests.

**Comment by niphlod** [comment]
BTW: didn't https://github.com/web2py/web2py/commit/6be3977fa76596b7235310aa4b26c424630ec69a fixed this already ?

**Comment by nursix** [comment]
Ahm - sorry @niphlod : my issue report here was about a real defect: the code in question introspected Py2 attributes but then accessed Py3 attributes. There is nothing applications can do to adapt to that, it's not a new feature nor an upgrade, but simply a mistake - and hence I raised the issue here and proposed a solution, which I think was totally legitimate - or what else do you have the issue tracking for? It's not a "complaint", it's a valid feedback I think.

And yes, that solution got implemented, so all fine in that regard.

The discussion started by @ilvalle was related, but not really a matter of concern for me. I just replied since being asked, and my standpoint is that backwards-incompatible changes at the framework level can (though they don't have to) make it much harder for established projects to get access to new features.

The new features (or improvements) that we want (need) to gain access to are completely unrelated to SQLFORM.grid() - which is currently the only thing that requires two parameters for representation functions. We're not even using SQLFORM.grid() anywhere.

Hence, that "fixing" of hundreds of our representation functions does not add any value for us, it's just an extra effort on top of the investments we already have to make for those new features and improvements/fixes that we really need.

And obviously, if we're forced to make extra investments that don't give us any value in return, then that is a problem. It's been manageable problem so far, but (and that is simply the truth) it has grown since PyDAL became an independent sub-project.

That's not a complaint, but just a fact - PyDAL has added a lot of value, but it has also imposed backwards-incompatible changes on us that did not give us any additional value, and thus made it increasingly painful for us to follow through.

Now, as much as I understand that there may be other projects that have benefited from those changes - I can not speak on behalf of the majority, but can only tell what such changes mean to our project. And the situation is simply that we are a very small team with a massive workload, and we simply don't have the capacity to follow major backwards-incompatible changes unless they add value to our project.

And the proposed change with enforcing 2-parameter represents simply doesn't.

Whether you value such feedback as useful input, or brush it off as unjustified "complaint", that is entirely up to you, and probably depends what you regard as your target audience. If you want to prioritize those teams which can afford backwards-incompatibility, then yes, you may have asked the wrong guy ;)

But if you don't want to hear a dissenting opinion, then why ask for it in the first place?

**Comment by niphlod** [comment]
hey @nursix , I wrote multiple "if"(s), all in the right places :P 

I value reports, and since these specific changes didn't break my own apps but seemed off to me too, I involved @ilvalle right away (he's the main "dealer" with py3 compat) . 
We were missing a test, @mdipierro ultimately fixed the issue, @ilvalle added the test, you can be sure it WON'T EVER happen again. And, it got closed in 13 days. "Flow-wise", it's one of the best bug reports, ever.

What I'm trying to "spread" (this is not the first time, both on github and in the forum, call me an evangelist) is that everybody wins when THIS happens INSTEAD of users spending time to adjusting code for a "stable-thingy" that was never reported to be broken in the first place. I *think* that that time *can* be a better investment *reporting*/*fixing*/*adding coverage* here rather than approaching maintainability "each one for its own". In *that* world, things like *we had to sacrifice in order to be able to run on a newer web2py version* won't happen.

**Comment by nursix** [comment]
I hear you @niphlod , but...

Your "EXCEPT that we can't really fathom every possibile usage (and mis-usage) without users adding regression tests and/or reporting bugs" makes me feel a bit devalued, and, to be honest, overcharged.

We are SAHANA, one of the oldest established web2py projects, and we have been using web2py as our application framework since long before 1.0. We have been adding features, reporting bugs and field-testing web2py in many mission-critical deployments for quite a long time - and we have had a suite of 600+ unit tests to detect regression long before web2py had any ;)

However, as much as we're trying to help here with our issue reports, we also have a project of 2million+ lines of code of our own to maintain - and are thus relying on you to take our problems seriously when it comes to costs of backwards-incompatiblity vs. value-add.

My point was that PyDAL has been moving very fast in the past 12 months (which was intended), and whilst that has added a lot of value, it has also added costs.

The main problem there wasn't so much to adapt our code to the PyDAL changes, but rather to keep it backwards-compatible for our downstream projects which do not necessarily use the latest web2py/PyDAL because their additional bits and pieces (e.g. co-apps, plugins) rely on older versions.

So, the cascade of impact with incompatible changes is a lot longer than it seems ;) - yet at the same time, there are changes we want to make use of simply because they fix problems. Managing that sometimes /does/ require to build fallbacks, and sometimes it also means to forego new features in web2py/PyDAL.

However, if asked for my opinion, then I can only disagree with a cost that doesn't give me any value in return. And what advantage do Py3 users get from /imposing/ 2 parameters for represents, especially if they (like us) don't use SQLFORM.grid?

I think that the current fallback implementation is good enough - and if the second parameter can indeed be unused, then I don't quite see why it needs to be enforced.

**Comment by niphlod** [comment]
this was really a no-brainer since it crashed py2.7, so it *needed* to be fixed. As for the "historical" presentation, I just might need to slap on the wrist who (us?) let those 600+ unittests slide and didn't "ported" them to web2py's CI. To be honest, I wasn't aware of that.
The "cascade effect" is duly noted, but again *that* world should be encouraged at *all* levels to make even **upstream** projects less hogged-down by **downstream** pieces and bits

**Comment by nursix** [comment]
Yeah, I wish it was that easy ;) but I'm afraid we have to deal with the /real/ world.

Our downstream projects are typically self-managed with low (or no) long-term development capacity. They can manage to do their initial modifications, but the most they can afford in terms of maintenance is to "git pull" our latest, and naturally they expect that to be as painless as possible.

We're trying to encourage them both to integrate upstream (so that we can take care of their mods) as well as to update early+often, but that is just wishful thinking in most instances. /That/ world in which humanitarian organizations can regularly afford continuous maintenance of IT solutions, I don't think it exists ;)

Although - I did succeed twice over the past two years :D so sometimes it does work. If we're lucky. Though - both were first-world deployments, backed by well-heeled sponsors, which isn't quite the norm for us.

The normal scenario is that when there is an emergency, they grab Sahana, modify it to fit their immediate needs (typically through a one-off contractor), and then they are busy using it while responding to the emergency. Then, once the dust has settled, they want to upgrade the core in order to pull in the latest fixes and feature adds - and who are we to tell them "sorry, you're out of date"? 

They are saving lives - while we're just writing code ;)

So we /are/ bogged down by downstream bits and pieces to some extent, and typically maintain backwards-compatibility for any of our features that do not /require/ a recent web2py version, even if those features are new. And currently, I think our oldest still-supported web2py is somewhere in the 2.11's, which I think is the average distance.

For the 2.14's I think we will have to maintain compatibility for at least the next 2 years, since there's a lot going on right now.

But as I say - all that is manageable so far, and I'm certainly okay with incompatible changes that do either not affect us (because we're not using the functionality), or gives us some value in return. I'm also ok with changes that are obviously necessary for the framework (such as consistency fixes), but I will remain in favor of painless migration paths and/or fallbacks wherever that is cheap or (like in this case) already exists.

Else, I certainly agree with your idea of how things /should/ be, but if everything was how it should be then we at SAHANA would be out of work. The fact that things out there are not how they should be is exactly what made us choose web2py - with it's guaranteed long-term backwards-compatibility and it's open ears for implementer problems ;)

And I know you can handle that - I've been watching you doing it long enough :D
