### ISSUE TITLE
Moved from controller cached function don't give any clue to the user about the issue

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1421]
When someone move a function from once controller file to another, if this function is cached... web2py keep trying to access the moved function in the previous controller file. We don't provide any clue to the user about the problem and we don't actually include code to avoid that. I mean, we surely can make a check controller file has change and if so update cache. Or at least we should add a more detailed message then "invalid function (default/myfunc)"... Something did you move this function from another controller if so, did you think to update cache if this function was cached previously.

Someone can reproduce this issue by creating a dummy() function with a cache decorator. Access the function view/page with a browser to load it in cache then move this function into another controller file (even without cache decorator) and access the page witht the proper controller file name... He will recieve invalid function and the controller specify will be the previous controller instead of the new controller.

**Comment by BuhtigithuB** [comment]
Maybe simply add this advice in the book would be the simplest way to solve this : 

```python
@cache('myfunc', time_expire=0 if 'controller_name' != request.controller else user_desired_time_expire)
def myfunc():
   ...
```

**Comment by niphlod** [comment]
uhm. this is a fine-print on the usage of cache.ram that just stores a pointer... that piece of code just wastes CPU for no sane reason... I mean, it's "good" that for rapid development you CAN change models and controllers and views and watch the outcome at runtime, but you SHOULDN'T rely on that for prod environments... recompiling and restarting the process SHOULD always be the way to go for prod.

**Comment by BuhtigithuB** [comment]
I remember having restart uwsgi, as my deployment fab function is doing it... I had move controller function in dev, no problem, when I push/deploy everything in prod the cache was causing issue... I do understand that checking if controller has change is a waste of CPU cycle in production... So I guess the only remaining option is to add some more details about possible moved decorate cached function.

**Comment by niphlod** [comment]
there's no way restarting the process you suffered the issue. Frankly one of the zen of python is "we're all consenting adults" and I'd refrain to add insane checks just to cover an ultra-edge case.

**Comment by BuhtigithuB** [comment]
as you which, I help someone with the issue this week, I thought about
cache, because I ran into this problem a couple of month ago, I would never
had a clue of the issue other than that...

Maybe mention it in the book (I would say at least), something like : if
you move  @cache('func') decorated function and you move it from one
controller file to another think to time_exprire it or restart web2py to
avoid running into weird issue where cache still point the the privious
controller file.

**Comment by niphlod** [comment]
given that nobody except the OP @BuhtigithuB added details, this is not to consider a web2py bug but merely a lack of documentation on the book. Opening an issue there to keep track (in the remote event someone is able to write english sentences vs contributing with python code to web2py ....)

https://github.com/web2py/web2py-book/issues/345

**Comment by abastardi** [comment]
I'm not sure I understand the problem here. Is the claim that when you move a function from one controller to another but try to access the *old* URL you get an "invalid function" error? If so, that has nothing to do with caching and is the expected behavior, as the old URL is not supposed to work any longer.

On the other hand, if you access the new URL, everything should work fine (no "invalid function" error). If you use the same cache key as before (which you should probably not do, as the cache key should include the full request URI), you'll get the old cached value, and otherwise, it will just generate a new cached value with the new key.

Note, the @cache decorator does not cache the function -- it creates an altered version of the function, which in turn caches its own output. Once the function is removed from the file, it can no longer be called, so web2py is not caching and calling any old functions.

If you are referring to some other behavior, please detail the exact steps to reproduce the issue.

**Comment by BuhtigithuB** [comment]
@Anthony

What I noticed is that if a function is @cache and actually cached because
been accessed recently, if you move it from one controller to another don't
work as you describe. I should reproduce this issue to remind myself
exactly what happen, though, I remember that web2py kind of access the
function in the previous controller file... I think I had change function
name at the same time, I am not sure, but I remember having hard time to
figure out what going on and how to fix the problem...

Will try to reproduce and create a dummy app so you can experiment it. I
may not describe the issue properly for you guys to understand...

:D

**Comment by abastardi** [comment]
@BuhtigithuB, I tried it myself and everything worked as expected:
- After moving the function, if you try the *old URL*, you get the expected "invalid function (default/myfunc)" error message.
- If you try the *new URL* and have used the same cache key (and the cached value has not expired), web2py returns the cached response. If the cached value has expired, you get a new response.

When you say, "web2py kind of access the function in the previous controller file," that doesn't quite make sense. The `@cache` decorator does not cache a function, nor could it result in web2py accessing an old function when a new URL is requested. When a request comes in, the requested controller is executed, with a call to the requested function *in that controller*. Any previous caching of returned values does not change the fact that web2py will execute the actual controller of the current request.

Of course, if you move/rename a function, you must change any URLs/links that point to the old function, otherwise you will get an "invalid function" error message -- but that is as expected and will happen whether or not you have used the `@cache` decorator.

Two additional notes. First, if using the `@cache` decorator on a controller action, the cache key should probably include the request URI, not just the function name. Second, even better would be to use `@cache.action`.

**Comment by BuhtigithuB** [comment]
I sure I remember entering proper url of the moved function
(controller/func), but web2py changing controller file name like
oldcontroller/func... I was entering url by hand in the address bar so the
issue was not cause by a wrong link remaining pointing over the old stuff...

**Comment by abastardi** [comment]
I cannot reproduce, and I do not think there is any mechanism by which web2py would/could do that, whether or not using `@cache`.

Are you saying you entered /newcontroller/func in the browser address bar and web2py did a redirect, such that the url in the browser address bar changed to /oldcontroller/func? Or are you saying that the browser address bar remained /newcontroller/func, but somehow internally web2py attempted to execute oldcontroller.py. It's not quite clear what you are claiming, but I don't see how either of these things could happen. I think you will need to produce a demonstration with real code.

**Comment by BuhtigithuB** [comment]
I mean the first, enter newcontroller/func and get redirect to
oldcontroller/func...

I give a try if I can reproduce.

**Comment by BuhtigithuB** [comment]
Sadly, I can't reproduced neither... Not sure if this because of Rocket...
When I experiment the issue, it was in prod with nginx... Also, I had
remove (delete old app) and deploy (copy) new app in place and restart
nginx/uwsgi... Not sure how could change anything... Will try to reproduce
it in prod...

On Thu, Sep 22, 2016 at 1:45 PM, Richard Vézina <ml.richard.vezina@gmail.com

**Comment by BuhtigithuB** [comment]
Haa! I reproduce it in prod... I get the wrong behavior that I mention, but
it not seems to be related to @cache at all... To reproduce it, it simple,
I just have to add stuff file (even just function into a controller I
think) without restart uwsgi...

Sorry for the false report... I thought it was related to cache because
when I remove cache decorator problem I had shade away... But I may had
make further operation then just remove the decorator... I am puzzled as
fabric deploy routine is supposed to restart all services... I also
remember having restart deployment many times...

I think it clear out this ticket which should definitly be closed

Thanks

On Thu, Sep 22, 2016 at 3:10 PM, Richard Vézina <ml.richard.vezina@gmail.com
> wrote:

> Sadly, I can't reproduced neither... Not sure if this because of Rocket...
> When I experiment the issue, it was in prod with nginx... Also, I had
> remove (delete old app) and deploy (copy) new app in place and restart
> nginx/uwsgi... Not sure how could change anything... Will try to reproduce
> it in prod...
>
> On Thu, Sep 22, 2016 at 1:45 PM, Richard Vézina <
