### ISSUE TITLE
bug in paths

### ISSUE THREAD

**Issue by RekGRpth** [web2py/web2py#1439]
solve:
```diff
git diff gluon/admin.py
diff --git a/gluon/admin.py b/gluon/admin.py
index 3eb3bc5..e0372ba 100644
--- a/gluon/admin.py
+++ b/gluon/admin.py
@@ -449,7 +449,7 @@ def create_missing_folders():
     """
     paths = (global_settings.gluon_parent, abspath(
         'site-packages', gluon=True), '')
-    [add_path_first(path) for p in paths]
+    [add_path_first(path) for path in paths]
 
 
 def create_missing_app_folders(request):

```

**Comment by niphlod** [comment]
whoops, mystypo. thanks for reporting

**Comment by ilvalle** [comment]
odds that this LOC is already covered by unittests (https://codecov.io/gh/web2py/web2py/src/b84b47dad252bacedbdd91a52394c628a950162d/gluon/admin.py#L452)
looking at the last travis.ci job there are a few failing tests https://travis-ci.org/web2py/web2py/jobs/156843763

**Comment by niphlod** [comment]
techinically web2py works if everything runs as normal, because of cwd and no libraries tested in site-packages .... needs fixing no matter what (on top of finding why loaded tests from pydal failing don't make the run fail). I'm issuing a PR right away

**Comment by niphlod** [comment]
@ilvalle: found at least a bit. I hate when I need to fix something that shouldn't need fixing, but love discovering bugs. 
a) the way we load tests for pydal... I guess @gi0baro did his best to make them run, but unfortunately cutting corners to have several runs on travis lead to tests being ran BUT not "merged" together in the main result. This means that in order to do a test run on travis for both mysql and postgresql (probably to lower the resulting matrix) we basically gave up tests. Giving that pydal itself doesn't do this, I'd go for restoring the matrix
b)  https://github.com/web2py/pydal/blob/master/tests/sql.py#L1466 groan

I'll open a new issue to discuss how to fix the mess.
