### ISSUE TITLE
update_or_insert returns none when updating

### ISSUE THREAD

**Issue by codylandry** [web2py/web2py#1503]
The dal update_or_insert method return None when updating.  This is fine when doing plain inserts or updates, but if you need to then create a foreign key reference to that row, you're left to query the id yourself if it was an update, which makes the method pointless in that case.  Can we have it return the id of the row in both cases?

**Comment by niphlod** [comment]
the "update" part can update several rows at once. Since it's meant to use as a "merge" tool (primarily), priority (in such cases a FK is needed) is biased to inserts. Usually a FK is generated at the first time an insert is performed. It's really a corner-case what you ask (retrieve the id at a later time to generate a proper FK). 
It's a documented behaviour (and a pretty solid one), so we are not going to change it:
- if it returns None, an update was performed
- if it returns an id, an insert was performed. 
There's no way to return a proper "something" in case of updates: if you need you can code the usual "check before insert" and retrieve the row(s) you want.
