### ISSUE TITLE
py3: Error importing csv file (using appadmin and in code) 

### ISSUE THREAD

**Issue by alexandremasbr** [web2py/web2py#1609]
When trying to import a csv file in appadmin, I get a flash message:
```
iterator should return strings, not bytes (did you open the file in text mode?)
```

I tried to import using code:
```
db.mytable.import_from_csv_file(open('db_mytable.csv', 'r'))
```

and got exactly the same message: 

```
<class '_csv.Error'> iterator should return strings, not bytes (did you open the file in text mode?)
```
I got it working in my code with 
```
db.mytable.import_from_csv_file(open('db_mytable.csv', 'r',encoding='utf-8'))
```
Looks for it works with python3, needs to be explicit declared the encoding.

**Comment by ilvalle** [comment]
Thanks for reporting, as you proposed such issue can be fixed by importing
```from gluon.fileutils import open_file```
and then, replacing 
```db.mytable.import_from_csv_file(open('db_mytable.csv', 'r'))```
with
```db.mytable.import_from_csv_file(open_file('db_mytable.csv', 'r'))```

Would you post a pull request with such fix?

**Comment by Juerodriguez** [comment]
Hi, this issue was fixed in https://github.com/web2py/pydal/pull/654, this changes until 21/05/2021 arent in web2py stable version. So I solved clone pydal in web2py/gluon/packages and rename pydal folder with dal.

Then in appadmin you just need call the method like this:

table.import_from_csv_file(file)
