### ISSUE TITLE
Auth add_membership and del_membership mistakenly alter the logged-in user's session

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1638]
Auth `add_membership` and `del_membership` not only add and delete records in the `auth_membership` table, but they also add and remove items from the `self.user_groups` dictionary of the currently logged in user (see https://github.com/web2py/web2py/blob/8a741023d8a2631a0a33dc47ee08f73e71018efc/gluon/authapi.py#L529).

The problem is that the `self.user_groups` dictionary should only be updated if the membership being added or deleted is for the currently logged in user. However, the code does the update regardless of the user_id. The following condition:

    if role:

should be changed to:

    if role and user_id == self.user_id:

**Comment by BuhtigithuB** [comment]
What about someone who change the membership of someone else??

**Comment by abastardi** [comment]
@BuhtigithuB, I'm not sure what you're asking, but that is exactly the problem. If User A (let's say an administrator) is logged in and adds or deletes a role for User B, the `auth.user_groups` list of *User A* will end up being altered, which is not what we want. The proposed code change ensures `auth.user_groups` gets changed only when the current user is adding or deleting a membership for themselves and not someone else.

**Comment by BuhtigithuB** [comment]
I though that these methods was suppose to allow user A (let's say an
admin) change membership of user B. I do understand that actually user
membership is momentarily wrongly updated... But is this change preserve
the expected behavior, I mean that admin can manage other users membership,
without them to logout and login again??

**Comment by abastardi** [comment]
These methods can be used to change the memberships of either the current user or another user. Regarding what you call the expected behavior (i.e., that an admin can change another user's membership without the other user having to log out and back in again) -- that is *not* the current behavior. If User A adds a membership for User B, the `auth.user_groups` list of User B will *not* be updated by `auth.add_membership`, as the current request has no access to User B's session (which is where the `auth.user_groups` list is stored). The problem is that the current code is mistakenly altering the `auth.user_groups` list of User A (i.e., the current user), even though the change was made for User B.

If User A makes a change for User B, User B will have to log out and back in again for User B's `auth.user_groups` to be updated -- the change I propose has no effect on that.

**Comment by BuhtigithuB** [comment]
Thanks for the explanation Anthony, I do agree that you found a non sens
bug... Now I have to scratch my head to understand why I have this behavior
in my app... I mean having a admin user able to modify other users
membership without them to need to log out and login again before the
change take effect..

**Comment by BuhtigithuB** [comment]
ok I understand, it because auth.hasmembership() which does a fresh query
each time...

How could we update someone else auth.user_groups?? Could we issue a one
time reinitialization command by setting a flag on/off when use
add_/del_membership?? We can then force a give user to reinit the
auth.user_groups list on his next request... I would requires more than a
flag if we don't want all the users to reintialize there auth.user_groups...

What do you think...

Here is not the place for talk about that, but if you think this could make
any sens I can create a ticket and make a feature request

This would make possible to avoid using auth.hasmembership() all over the
place and trigger a bunch of queries at each request...

On Tue, Jun 6, 2017 at 10:04 AM, Richard Vézina <ml.richard.vezina@gmail.com

**Comment by abastardi** [comment]
> How could we update someone else auth.user_groups?? Could we issue a one time reinitialization command by setting a flag on/off when use add_/del_membership?? We can then force a give user to reinit the auth.user_groups list on his next request...

That's one approach, but then we need a way to persist the list of flagged users (preferably that easily scales horizontally), and there would be some cost on every request (at least every request that needs to check authorization) to check the list.

Another option would be to keep a record of active session identifiers for each user, and whenever a role change occurs, update all of that user's active sessions (note, this will not work with cookie-based sessions -- only sessions stored on the server).
