### ISSUE TITLE
Auth change_password does not enforce settings.password_min_length

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1800]
In authapi.py at https://github.com/web2py/web2py/blob/c4e08eeeb34cb51d9048a0eabc07586494ac8c8c/gluon/authapi.py#L991 and in tools.py at https://github.com/web2py/web2py/blob/c4e08eeeb34cb51d9048a0eabc07586494ac8c8c/gluon/tools.py#L3696, the `change_password` code sets the `CRYPT` `min_length` attribute to `0` (so the minimum length requirement will not be enforced on the old password). However, the instance of the `CRYPT` validator that is mutated is still the same instance attached to the `db.auth_user.password` field, so the subsequent validation of the new password does not enforce any minimum length.

The code should instead create a copy of the existing `CRYPT` validator rather than mutating the existing one.

**Comment by leonelcamara** [comment]
Eh, funny bug, which is happening because supposedly that would only be applied to validate the old_password but we change IS_CRYPT instance which is used later for the new_password, I guess this is my fault for not thinking it through when I made the authapi refactor and just copying the old behaviour as it was. I'll look into it.
