### ISSUE TITLE
UnicodeDecode error setting up session

### ISSUE THREAD

**Issue by bnmnetp** [web2py/web2py#1861]
Hi,

Excited to see all the progress on python3.  I decided to setup a fresh install of Ubuntu 17.10 and give my app a try against master.  I get this traceback:

```
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/models/db.py", line 24, in <module>
    session.connect(request, response, masterapp='runestone', db=db, migrate='runestone_web2py_sessions.table')
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 965, in connect
    row = table(record_id, unique_key=unique_key)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 573, in __call__
    orderby_on_limitby=False).first()
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 2254, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 762, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 741, in _select_aux
    return processor(rows, fields, colnames, cacheable=cacheable)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 305, in parse
    for row in rows
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 305, in <listcomp>
    for row in rows
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 231, in _parse
    value = self.parse_value(value, fit, ft, blob_decode)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/adapters/base.py", line 198, in parse_value
    return self.parser.parse(value, field_itype, field_type)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 101, in parse
    return self.registered[field_itype](value, field_type)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 76, in __call__
    return self.call(value, field_type)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/parsers/__init__.py", line 73, in _call
    return self.f(self.parser, value)
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/parsers/base.py", line 37, in _blob
    return to_native(b64decode(to_bytes(value)))
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/_compat.py", line 82, in to_native
    return obj.decode(charset, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

The sessions table is created and is there from a separate script I run to initialize the database.  there is even one row in the table.  Let me know what else I can get to help debug.

Brad

**Comment by dartg** [comment]
The problem is that the `session` object is pickled and stored in a `blob` field, which by default does the following when retrieved from the database (`pydal/parsers/base.py:35`):

```
    @for_type('blob')
    def _blob(self, value):
        return to_native(b64decode(to_bytes(value)))
```

The `to_native` function tries to decode from utf-8, which raises the error since the pickled data is not a valid utf-8 string. Since the `blob` field stores binary data, the result in Python 3 should be `bytes`, not `str`. Then the following should fix the issue:

```
    @for_type('blob')
    def _blob(self, value):
        ret = b64decode(to_bytes(value))
        if PY2:
            ret = to_native(ret)
        return ret
```

However the changes should be made in the pyDAL repository. I can create a pull request there but I would like to hear feedback from the experienced contributors before!

**Comment by ilvalle** [comment]
Pydal stores a blob field as b64encoded characters, your error is odd.
Did you try to start with py3 with an empty session table?

**Comment by dartg** [comment]
I already did that and the error came up. I insist in that blob fields should be returned as `bytes` in Python 3. Even the error is pretty explicit:

```
>>> import pickle
>>> a = 1
>>> pickle.dumps(a).decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid
start byte
```

**Comment by bnmnetp** [comment]
@ilvalle - Yes, I created a brand new VM and set up everything cleanly.  The sessions table was totally empty when I started.

**Comment by ilvalle** [comment]
@bnmnetp `pickle.dumps(a)` returns bytes encoded as `latin1`
```
>>> import pickle
>>> a=1
>>> pickle.dumps(a).decode("latin-1")
'\x80\x03K\x01.'
```
@mdipierro @gi0baro @leonelcamara as shown by @bnmnetp, blob fields are broken if you save `latin-1` encoded objects. Any idea?

**Comment by leonelcamara** [comment]
@ilvalle I don't have much experience with blobs with web2py, but why are we even messing with the encoding with them? A blob should just return whatever the b64decode returns, which will be "bytes" in python 3 and "str" in python 2. I would actually simplify @dartg fix suggestion and make it simply:

    @for_type('blob')
    def _blob(self, value):
        return b64decode(to_bytes(value))

**Comment by ilvalle** [comment]
@leonelcamara is your proposal backwards compatible? In addition, it will return always bytes even if you inserted a unicode string.
What do you think if bytes are returned only when the decoding fails?
```
@for_type('blob')
def _blob(self, value):
    decoded = b64decode(to_bytes(value))
    try:
        decoded = to_native(decoded)
    except:
        pass
    return decoded
```

**Comment by leonelcamara** [comment]
It may be backwards incompatible but I think what we had previously was simply a bug. If you store a unicode string in a blob you should be responsible for encoding and decoding it. A blob is simply binary data you need to know how to interpret those bytes, why would pydal assume the bytes are a string and decode it.  
  
The only backwards incompatibility I can remember is due to the session and it can be fixed there:
Changing:

    session_data = pickle.loads(row.session_data)
to:

    session_data = pickle.loads(to_native(row.session_data))

**Comment by dartg** [comment]
@leonelcamara @ilvalle Right. Actually, `to_native(...)` is doing nothing in Python 2 since `b64decode()` already returns `str`. So even now blob fields return `str` whether you inserted unicode or not.

**Comment by ilvalle** [comment]
@dartg would you test https://github.com/ilvalle/pydal/tree/fix_blob

**Comment by dartg** [comment]
@ilvalle I would go with @leonelcamara fix:

```
@for_type('blob')
def _blob(self, value):
    return b64decode(to_bytes(value))
```

That's 100% backwards compatible in Python 2. In Python 3 it will probably break applications expecting a `str` object to be returned from a blob field, which was a bug.

I think the real bug is actually letting `unicode` (py2) / `str` (py3) objects to be inserted into blob fields and implicitly encoded. Only `str` / `bytes` objects should be allowed (maybe it could be discouraged in the docs?), but that will efectly break many applications.
