### ISSUE TITLE
SQLFORM  : two translation issues

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#1863]
1) First issue: 
upload widget: following fields are never translated. 
'Choose File'
'No file chosen'
'file'
2) Second issue. 
In smartgrid, on the '+' button of the top left of the form, the standard title is 'Add record to database'. If you change this title for instance to 'your own title', the translation always refers to 'Add record to database'  and not to 'your own title'.

**Comment by leonelcamara** [comment]
1. This is not a web2py bug, that is a browser widget and the browser decides its language.  
2. You need to set the title using T('your title') if you want it to go through translation.

**Comment by sbourgeois1** [comment]
Thanks for your response.
1. Yes,I know it is more difficult than the usual translation, but I think this could be solved with a javascript function which could be integrated in the framework.
2. This is of course what is done, and what does NOT work correctly. The system always makes the translation of the text 'Add record to database', and not the translation of what you put in the title, even if you use the T helper to translate. Read again the second issue...

**Comment by leonelcamara** [comment]
1. You and others can make a custom file widget and preferably even share it in github, I don't think it should be included by default in web2py as it's non standard browser behavior and there is an infinite number of file upload widgets using different libraries you could make.  
2. Humm you're right, apparently there's no option to change the grid texts. You can change them by using serverside DOM manipulation. Otherwise probably close this issue and open a new one asking for the texts to be customizable the same way the UI is, as the grid could get a messages dict as an argument too.

**Comment by sbourgeois1** [comment]
1. Thanks for your suggestion. Unfortunately, I do not have enough technical know how to do this in a reasonable time.
2. Ok. I open e new ticket.
