### ISSUE TITLE
Documentation or website incorrect

### ISSUE THREAD

**Issue by KonigKlack** [web2py/web2py#2165]
The documentation states that Python 2.5 is required (Page 31) however your site states that 2.6 is no longer supported and 2.7 or 3.5+ are required (http://www.web2py.com/init/default/download).
Just looking for clarification before attempting to suggest any changes to anything. 

After further reading of the documentation, it is unclear whether web2py would run on a system that contains only Python 3.5+ or if Python 2.7 would be absolutely required. If Python2.7 is an absolute requirement, is this only for web2py to function or must all code be 2.7 syntax as well? 
I'll admit, I'm writing this and updating it as I read. 

With clarity, I would be more than willing to update the documentation.

**Comment by nicozanf** [comment]
Hi,
we are working on updating the manual and the documentation, but this is a long running task. This particular phrase has already been updated on the online manual (see http://web2py.com/books/default/chapter/29/01/introduction#Why-web2py), but the PDF version is not.
So, it's better to use the online version of the manual and be prepared to have some examples that will not work right because they're not already Python 2.7 ready.
All code must be 2.7 compatible in order to work with recent web2py version. And if you're starting now with Python / web2py I suggest you to start with Python 3 directly.

**Comment by KonigKlack** [comment]
Well I use Python 3.7, so I need to build my web2py apps with 2.7?

**Comment by nicozanf** [comment]
No, if you run web2py from source with python 3.7, it will run all your web2py applications under python 3.7 - you cannot mix them
