### ISSUE TITLE
Validation messages of extra fields in auth_user don't comply with available translations

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2168]
When creating extra fields for auth_user, the validation messages for those fields are always in English. They don't comply with the translations available.

This does not happen on the default fields.

I added this to db.py
```
auth.settings.extra_fields['auth_user'] = [
    Field('pagination',
          'integer',
          default=9,
          label=T('Pagination'),
          notnull=True,
          required=True,
          requires=IS_INT_IN_RANGE(5, 51),
    ),
]
```
When inserting an invalid value, the returned message is always

> Enter an integer between 5 and 50

even when the web2py language is not English and the languages files have the correct translation available.

web2py 2.18.4
Python 3.7.1 x86
Firefox 66.0.2 x64
Windows 7 Pro x64 SP1+all updates

**Comment by jcrmatos** [comment]
I have confirmed that it is indeed a bug in web2py.
If I add
`T.force('pt')`
before 
```
auth.settings.extra_fields['auth_user'] = [
    Field('pagination',
          'integer',
          default=9,
          label=T('Pagination'),
          notnull=True,
          required=True,
          requires=IS_INT_IN_RANGE(5, 51),
    ),
]
```
the validation messages all come out in Portuguese (even if I change the language to English).

So the problem is that the code for the extra_fields is not language independent.

**Comment by abastardi** [comment]
Note, the issue is that default error messages in all validators used to be translated automatically, but that was changed when validators were moved to pydal in web2py 2.18. I would consider that a break in backward compatibility, as it now requires every validator in every application to be updated with a custom error message wrapped in `T()`, rather than relying on the default error messages.

**Comment by abastardi** [comment]
Note, this is not an issue with Auth `extra_fields`, but a more general issue involving the `IS_*_IN_RANGE` validators, which create the translated error message at instantiation (possibly before the translation language has been set) rather than at validation time. See https://groups.google.com/d/msg/web2py/7O_h5YotOsQ/HS2czDDyCAAJ.

In those validators, it should be possible to move error message logic from the `__init__` method to the `validate` method.

Note, this issue belongs in the pydal repo, as the validators have been moved there.

**Comment by jcrmatos** [comment]
Thanks.

I was told by Anthony in the web2py group the exact same thing write now.
https://groups.google.com/forum/#!topic/web2py/7O_h5YotOsQ

"
The problem is unique to the IS_*_IN_RANGE validators, all of which create a translated error message at the time they are instantiated rather than at validation time. For example, here is the init code for IS_INT_IN_RANGE:

pydal/pydal/validators.py

Line 817 in e973f27
 self.error_message = range_error_message( 
.

So, you need to set the translation language before defining one of these validators. Note, this has nothing to do with Auth extra_fields, just with the point in the code at which the validators are defined.

I don't see why the error message logic cannot be moved from the init method to the validate method in these range validators, which would push the translation to validation time, as with all the other validators. So, feel free to submit an issue about this in the pydal repo and refer to this post (or better yet, make a pull request).

Anthony
"

**Comment by jcrmatos** [comment]
I opened the issue in pydal.

**Comment by abastardi** [comment]
> I was told by Anthony in the web2py group the exact same thing write now.
> https://groups.google.com/forum/#!topic/web2py/7O_h5YotOsQ

Yes, that was me.
