### ISSUE TITLE
Web2py change field type by itself

### ISSUE THREAD

**Issue by marcobra** [web2py/web2py#2203]
**Describe the bug**

2.18.5-stable+timestamp.2019.04.08.04.22.03 
(Running on Rocket 1.2.6, Python 2.7.15rc1) 

in a table with migrate=True:

`Field('numero', 'integer', requires = IS_NOT_EMPTY(),label="Numero cdu"),`

the result table in application storage set the "numero" field as string type, seems the culprit is "requires = IS_NOT_EMPTY()"

**To Reproduce**
1. please see the above description 

**Expected behavior**
Send error to user and do not auto change field type from integer to string 

Thank

**Comment by jvanbraekel** [comment]
Hello,

You may have find the solution in the meantime, since this is likely a miscomprehension on your side more than a bug. 'IS_NOT_EMPTY' is a string validator...  You should use the 'requered=True' and/or notnull='True' field's parameters to archive your goal instead.  The first will create a  'not null' constrains at the database level, the last a mandatory validation check at the form level.
