### ISSUE TITLE
DAL returns incorrect record ID on MySQL insert when manually specifying the ID value

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#667]
_From [ABasta..._at_gmail.com](https://code.google.com/u/103720714265511973715/) on August 07, 2013 13:32:17_

See https://groups.google.com/d/msg/web2py/ipXEtxUbt2w/z_7iDdEuK6wJ . We may be able to use conn.mysql_insert_id(), at least when using the MySQLdb driver.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1620_

**Comment by niphlod** [comment]
_From [ABasta..._at_gmail.com](https://code.google.com/u/103720714265511973715/) on August 07, 2013 04:33:45_

Note, this is relatively low priority, because if you manually specify the ID, you shouldn't really need its value to be returned. But this issue could cause confusion or lead to subtle bugs in user code.

**Comment by sp1d3rx** [comment]
MySQL last_insert_id() is wacky and not at all reliable. I wouldn't recommend using it, as it will set the last_insert_id only on autogenerated columns, and even when inserts were not successful. Furthermore, on multiple row insertions, it returns the first generated id, not the most recent one. 

I'd vote to not fix this one and politely suggest people who have chosen MySQL to upgrade to Postgresql.

**Comment by niphlod** [comment]
I'm no fan of mysql either, but saying it's wacky is way too exagerated for the requirement it has on DAL. 
If we want to bash mysql, let's bash it for real reasons, but.........if an issue needs to be rejected, it has to be for the correct reasons.

If you want the id of the last inserted value, it HAS to be autogenerated. 
If you choose in your code the "id", there's no reason for DAL to return anything valuable. 
The same thing goes for every backend out there.
"on multiple row insertions, it returns the first and not the last" is not an issue either, because last_insert_id() is used on a single insert() statement from DAL, that can only send 1 row at a time, and there is no bulk_insert() facility on DAL.
Ultimately, "even if the inserts were not successfull" is not something that bother us. It fails well before returning the value.

The issue at hand "should" be discarded because the value returned by db.table.insert(....) needs to be "truthful" only in the case the value is not known beforehand, which is obviously ONLY the case where it is autogenerated. This could be circumvented using mysql_insert_id(), with no issues whatsoever for the use DAL needs to fullfill. 

BTW: the whole issue is kind of silly, since DB API states that the information DAL needs is cursor.lastrowid. Don't really know why DAL is working out these intricacies when the DBAPI should give the exact thing we need (https://www.python.org/dev/peps/pep-0249/#lastrowid) .

@abastardi , @mdipierro : thoughts ?

**Comment by niphlod** [comment]
@gi0baro : I'll leave this up to you. I'd close this if cursor.lastrowid is effectively not more stable than the current method. Issues like these shouldn't take two months of mumbling :-P

**Comment by gi0baro** [comment]
Ok, I've opened a separated issue on pyDAL to update mysql `lastrowid` method, since the `cursor.lastrowid` is a cleaner choice for the code.
Regarding the "issue" itself, I'm gonna close this since, as you pointed out, is pointless to get the `id` value for an inserted row with a chosen id value.

**Comment by Jimi-James** [comment]
This NEEDS to be either fixed or clearly documented. I just spent hours pulling my hair out, wondering why I couldn't get the row I was looking for after using the update() function (yes, not insert(), but update()). I was using update()'s return value instead of the specified id because I had copy+pasted the code from a different function, meant to only insert, and I thought, why not just leave it at that.

Finally, I figured out that update()'s return value was not the right row number. I should not have had to go through that. It should have either not happened at all, or been extremely easy to know about and predict from the beginning.

**Comment by abastardi** [comment]
@Jimi-James, your problem is not related to MySQL or this issue. Note that the `.update` method operates on a `Set` object and can affect multiple records in a single operations. Therefore, it would not make sense for it to return a record ID, as there would not necessarily be a single record ID to return (it would also be inefficient, as returning IDs of updated records would require a subsequent select). This is why the Python DB-API [`cursor.lastrowid`](https://www.python.org/dev/peps/pep-0249/#lastrowid) attribute is expected to be defined only for single-record *insert* operations and why only the DAL *`.insert`* method returns a record ID. The `.update` method, on the other hand, returns the *number of records* updated (0 if no records were updated).

**Comment by Jimi-James** [comment]
Oh, so it was me misreading the docs. Whoops.
