### ISSUE TITLE
Avoid inserting duplicate archive records with record versioning

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#718]
_From [kjkuan_at_gmail.com](https://code.google.com/u/kjkuan_at_gmail.com/) on August 13, 2014 17:54:52_

Given a table with record versioning enabled, for every successful update operation a row will be inserted in the archive table. It would make sense to only insert an archive row when there's a difference between the old row and the new row.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1966_

**Comment by kjkuan** [comment]
I believe this had been fixed and merged both in the web2py repository and the dal repository before 2.9.12 was released..., but somehow it's not in the `web2py_src.zip` download.

See [here](https://github.com/web2py/web2py/pull/568) and [here](https://github.com/web2py/pydal/pull/9)

Also, since dal is now in a separate repository, perhaps web2py should track it via git submodule? Just a suggestion.

**Comment by kjkuan** [comment]
ok just checked again, it actually didn't get merged into the web2py repo, but only to the pydal repo.

**Comment by niphlod** [comment]
so, I think this should be closed. Feel free to add a comment if you're noticing issues.
