### ISSUE TITLE
session.renew() should delete the file/DB record

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#735]
_From [mandarv..._at_gmail.com](https://code.google.com/u/108507264684706694414/) on October 17, 2014 20:10:01_

https://groups.google.com/d/msg/web2py/j-GwnDc0G6g/MZAyrmn4BVcJ As part of this discussion - Anthony asked to open an issue. What is the expected output? What do you see instead? session.renew() just "clears" the underlying Storage() object.
but the files/DB record remains.
This could lead to session hijacking security issue - since such "renewed" session can be used by attacker - and since the file/DB record remains, it is used as a "valid" session (Then what is the use of renew() ?) What version of the product are you using? On what operating system? 2.9.5 + linux
But this isn't likely OS specific Please provide any additional information below. gluon/global.py : Session.clear() should have code to delete the file/db record after the Storage.clear() is called.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1999_

**Comment by maxslimmer** [comment]
This doesn't work (at least on Windows). There are at least two reasons that I could figure out:
1. The unlink(target) errors because the target file is still in use. I think this can be resolved by calling self._close(response) before unlink().

2. When I apply the above, the target is removed but the parent and grandparent folders are not. I worked out a solution using fileutils.recursive_unlink but it had an issue when running at full speed (i.e. not stepping in a debugger).

**Comment by niphlod** [comment]
what version are you on ?

BTW: 
1) should work
2) will never take place (too many resources involved for no improvement): just clear regularly sessions to prune empty folders

**Comment by maxslimmer** [comment]
1)  2.10.4.  I can upgrade and try to reproduce but it looks like the this commit was included in my version.

2) Yup, ok.

**Comment by niphlod** [comment]
1) you're right but you never know...although the idea of unlocking before unlinking doesn't sound bad

**Comment by niphlod** [comment]
closed by #1058
