### ISSUE TITLE
{{include}} vs {{block}} unexpected behavior

### ISSUE THREAD

**Issue by michele-comitini** [web2py/web2py#772]
Kudos to Paolo Dente (AKA @pgcd) for finding what follows

How to reproduce:
------
 - create a new app
 - views: a.txt, b.txt, c.txt

a.txt
------
```
{{block content}}
this block content in a
{{end}}
in a before extend
{{extend}}
in a after extend
```
b.txt
------
```
in b before extend extend 'default/a.txt'
{{extend 'default/a.txt'}}
in b after extend extend 'default/a.txt'
{{block content}}
this block content in b before super
{{super}}
this block content in b after super
{{end}}

```
c.txt
------
```
this is c before include
{{block content}}
{{super}}
this is block content in c
{{end}}
{{include 'default/b.txt'}}
this is c after include
```

Start the shell:

```bash
$ python web2py.py -M -S <app name>
```

```python
>>> print response.render('default/c.txt', {})
```

Result:
```
this is c before include


this is block content in c

in b before extend extend 'default/a.txt'


this is block content in c

in a before extend

in a after extend

this is c after include


```

The {{block}} from the including file (c.txt) is read but duplicated.
{{super}} in c is completely ignored.
N.B. {{super}} in b is completely ignored if {{block}} is not present in c.txt

Expected result:
---
{{block}} in c.txt not duplicated
{{super}} in c.txt taken from {{block}} defined in a.txt

**Comment by sp1d3rx** [comment]
I'm not seeing this as a bug. Yes, it's confusing, but that doesn't mean it's a bug. Here's my view of what is happening...


a.txt

1. {{block content}}
2. this block content in a
3. {{end}}
4. in a before extend
5. {{extend}}
6. in a after extend

b.txt

1. in b before extend extend 'default/a.txt'
2. {{extend 'default/a.txt'}}
3. in b after extend extend 'default/a.txt'
4. {{block content}}
5. this block content in b before super
6. {{super}}
7. this block content in b after super
8. {{end}}

c.txt

1. this is c before include
2. {{block content}}
3. {{super}}
4. this is block content in c
5. {{end}}
6. {{include 'default/b.txt'}}
7. this is c after include



1 1c. this is c before include			-- start rendering c
2 4c. this is block content in c		-- continue rendering c. Note this sets the block "content" to whatever C is, regardless...
3 1b. in b before extend extend 'default/a.txt' -- hits the include, renders b until 7
4 4c. this is block content in c 	-- rendering b		-- extending a and a has block "content" which is now "content" block from c...
5 4a. in a before extend			-- rendering b		-- finishing rendering a
6 6a. in a after extend				-- rendering b		-- finishing rendering a
7 7c. this is c after include		-- finish of c


The thing is, you are trying to use 'super' without extend, which is why that is ignored.
The block in c is duplicated because it's the same name as the block from a, and 'block content' in a is replaced when c's block is defined first before including b.

**Comment by abastardi** [comment]
I haven't followed all the details here, but I don't think it makes sense to have an `{{extends}}` without specifying a file to extend (this does not apply to `{{include}}`, which can be used on its own to indicate where an extending view should be inserted).

**Comment by sp1d3rx** [comment]
Michele this is not a bug. See my explanation above. 

Abastardi I agree.

**Comment by michele-comitini** [comment]
sp1d3rx and Anthony  I agree on your analysis I suppose the correct fix
should be that if {{extend}} has no file than it should fail right away
with proper error.  Does that make sense?


2015-06-10 4:30 GMT+02:00 sp1d3rx <notifications@github.com>:

**Comment by abastardi** [comment]
Note, you should be able to do `{{extend python_expression}}` where `python_expression` potentially evaluates to `None` (as a way of doing a conditional extend), but you shouldn't be able to do `{{extend}}`.

**Comment by leonelcamara** [comment]
So an empty extend cannot throw an error because the python expression can be evaluated to None so this is definitely not a bug and should be closed.

**Comment by niphlod** [comment]
@leonelcamara : without any further note in the book and/or in the code ?
@abastardi , @mdipierro thoughts ?

**Comment by michele-comitini** [comment]
can be closed.  An explicit reference to None behavior would help of course.

2016-03-29 15:08 GMT+02:00 niphlod <notifications@github.com>:
