### ISSUE TITLE
Web Editor save hangs if web2py path is not ANSI

### ISSUE THREAD

**Issue by ASalazarMX** [web2py/web2py#778]
If web2py's parent folder contains special characters, the web editor never completes a save with syntax errors. The file is saved, but the "saving..." message never disappears, and retrying the save triggers a file merge.

**Steps to replicate the error**
* Install web2py from web2py.com/examples/static/web2py_win.zip
* Unzip to **c:\código\web2py**
* Edit the welcome application, make a syntax error and save

**Workaround**
* Rename **c:\código\web2py** to **c:\codigo\web2py** or any ANSI name

**Comment by niphlod** [comment]
this is not a problem of web2py per-se but a hiccup in what the exception representation is "spitted-out" by python. Everything works as expected, but in order to print the exception, the admin app creates a flash message containing PRE(str(e)), where e is an exception. Unfortunately, the string representation on python 2.7 on Windows with unicode paths is screwed, so it doesn't get escaped properly, and in turn the javascript can't decode it properly. 

The "solution/workaround" here is - and would only be - doing PRE(repr(e)), which roughly translates

    expected an indented block (C:/Users/Administrator/Desktop/codigo/web2py/applications/welcome/controllers/default.py, line 11)

to

    IndentationError('expected an indented block', ('C:/Users/Administrator/Desktop/c\xf3digo/web2py/applications/welcome/controllers/default.py', 11, 1, '1/0\n'))

I personally started hating admin a long time ago, so I'm not really against the change, for the simple reason I don't really use it. 
BTW: this took me the last hour to pinpoint.
@mdipierro : final decisions ?

**Comment by niphlod** [comment]
@mdipierro : ping !
