### ISSUE TITLE
DAL > MSSQLAdapter & MSSQL2Adapter > ILIKE fails for text and ntext columns

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#786]
_From [score2..._at_gmx.net](https://code.google.com/u/100357035028011448959/) on February 05, 2015 11:38:16_

The LOWER() sql statement in ILIKE() does not support text and ntext columns.

Bugfix: use the old LIKE for MSSQLAdapter & MSSQL2Adapter
     def LIKE(self, first, second):
        """Case sensitive like operator"""
        return '(&#37;s LIKE &#37;s)' &#37; (self.expand(first),
                                 self.expand(second, 'string')) What version of the product are you using? On what operating system? 2.9.12

Maybe invalidates issue #2044

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2045_

**Comment by niphlod** [comment]
this has been, and will always been a problem for legacy mssql. 
There's no way to do a case-insensitive like() on text fields. Fortunately, if you're on MSSQL >= 2005, you can avoid using 'text' fields in favour of "varchar(max)". just use mssql3 (>= 2005), mssql4 (>=2012) to use the newer mssql features, and you're good to go

**Comment by skoa-h** [comment]
I try to avoid text but list:reference is using text columns and there the bug popped up for me after the default behaviour of contains was changed.

For a case-insensitive like() there is maybe this workaround?
http://stackoverflow.com/questions/8314218/sql-search-for-values-in-a-field-with-text-datatype-regardless-of-casing

**Comment by niphlod** [comment]
what adapter are you using specifically ? The collate trick doesn't do the job in numerous side-cases.

**Comment by skoa-h** [comment]
Sorry for the late reply, I'm using the MSSQLAdapter on a live db.

**Comment by niphlod** [comment]
ok. rephrase .... mssql:// , mssql2:// , mssql3:// or mssql4:// ?

**Comment by skoa-h** [comment]
Sorry for not replying at all, I never get any email from github.

Can this bug be reopened?

By Updating to web2py 2.11.2 MSSQLAdapter, MSSQL2Adapter and MSSQLNAdapter will not work most of the time caused by the base ILIKE implemenation.
I did a workaround by not using case_sensitivity at all in older web2py versions.

I'm using mssql:// in my project.

The ILIKE implementation needs either a distinction for fieldtype == "TEXT" / "NTEXT" where it cannot use LOWER() or don't use lower at all.

For MSSQL2Adapter something like this (not a real bugfix):
`
def ILIKE(self, first, second):
	second = self.expand(second, 'string').lower()
	if second.startswith("n'"):
		second = "N'" + second[2:]
	if fieldtype in ('text', 'json', 'list:integer', 'list:string', 'list:reference'):
		return '(%s LIKE %s)' % (self.expand(first), second)
	else:
		return '(LOWER(%s) LIKE %s)' % (self.expand(first), second)
`

**Comment by niphlod** [comment]
mssql and mssqln are to be used with MSSQL 2000. Switch to higher adapters if you are on newer versions. The new recommended one will soon be mssql4n
