### ISSUE TITLE
Define unique=True for username and/or email in auth_user table by default

### ISSUE THREAD

**Issue by rayluo** [web2py/web2py#921]
Otherwise there would be a slim (sometimes noticeable) chances of duplicated records go into database.

This proposal could bring a rare (0.01%?) chance of a user-scary 500 error ticket when duplication happens, but it ensures 100% guarantee of no duplication in the very important auth_user table.

PS: There was a lengthy conversation [here](https://groups.google.com/forum/#!topic/web2py/tsRK_e_TRZU).

**Comment by mdipierro** [comment]
This breaks record versioning which is an important feature of auth.

**Comment by rayluo** [comment]
Fair enough. Agree with the decision. I'll use other approach to address the original problem. Thanks!

**Comment by sbourgeois1** [comment]
Related topic: in case of CAS change, I observed that in the local auth_user table, there is a duplication of record with same email address, even if unique=True for the email. Can I suggest to update the auth_user.registration_id field with the new cast address rather than adding a new record in the auth_user table?

**Comment by rayluo** [comment]
@sbourgeois1 I'm not the one to answer your question above, but I would suggest you to create a separated issue for your question, rather than commenting on an already-closed issue. Otherwise your comment might not be very visible to the community.
